### ISSUE TITLE
Criar as novas categorias  de notícias no WP

### ISSUE THREAD

**Issue by marilucchesi** [pensandoodireito/pensandoodireito-tema#14]
categorias:
Assuntos Legislativos
Debates Públicos
Editais
Entrevistas
Eventos
Opinião
Pesquisas
Ainda vamos ter mais duas, que vão funcionar basicamente como filtros(não sendo "categorizáveis" no cadastro de notícias), porém serão tratadas como categorias automáticas:
Recentes
Mais Lidas

**Comment by diraol** [comment]
Issue transferida para o repositório "pensandoodireito-sitebase"

**Comment by marcoamarelo** [comment]
participacao-sitebase

Marco Antonio Konopacki

## @marcoamarelo

...... __@
...._ \ >_
...(_)/ (_)

2015-04-01 15:29 GMT-03:00 Diego Rabatone Oliveira <notifications@github.com
