### ISSUE TITLE
BREADCRUMB - corrigir texto de Publicação para Publicações

### ISSUE THREAD

**Issue by marilucchesi** [pensandoodireito/pensandoodireito-tema#21]

**Comment by diraol** [comment]
Aonde é para fazer essa correção @marilucchesi  ?

**Comment by diraol** [comment]
@marilucchesi Quando se está na página "archive-publicacao", aonde tem a lista de publicações, aparece "Publicações" no breadcrumb. Já quando está na página de uma publicação específica aparece "Publicação". Não era o comportamento esperado?

**Comment by marilucchesi** [comment]
@diraol eu acho que o esperado quando estiver dentro de uma publicação seria:
HOME  > PUBLICAÇÕES > NOME DA PUBLICAÇÃO ABERTA, rola? Tá assim?

**Comment by diraol** [comment]
Issue transferida para o repositório "pensandoodireito-sitebase"
