### ISSUE TITLE
PUBLICAÇÕES - limitar caracteres na descrição

### ISSUE THREAD

**Issue by marilucchesi** [pensandoodireito/pensandoodireito-tema#24]
máx 200 caracteres (com css/gradiente)
![captura de tela 2015-03-23 as 17 25 32](https://cloud.githubusercontent.com/assets/10927020/6789791/c4f4cf06-d181-11e4-95ae-0f4fcc2fec87.png)

**Comment by marilucchesi** [comment]
@thsl depois do @diraol ajustar, vc dá uma olhada pra criar o css do gradiente, blz?

**Comment by diraol** [comment]
Issue transferida para o repositório "pensandoodireito-sitebase"
